#!/usr/bin/env python3
"""Plot the HI produced by the trained N-CMAPSS paper-replay model.

The input CSVs were generated by ``reproduce_n_cmapss_lstm_ae_paper.py`` and
therefore already contain model reconstruction losses for every development
and test flight.  This script only reorganizes those model outputs into an
all-engine figure and a convenient combined CSV.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd


DEFAULT_MODEL_DIR = Path("outputs/N-CMAPSS/lstm_autoencoder_paper/DS02-006")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model-dir", type=Path, default=DEFAULT_MODEL_DIR)
    parser.add_argument("--output-dir", type=Path, default=None)
    parser.add_argument("--hi-column", choices=("hi_paper_9", "hi_all_13"), default="hi_paper_9")
    return parser.parse_args()


def load_scores(model_dir: Path) -> pd.DataFrame:
    model_path = model_dir / "paper_lstm_ae.pt"
    metadata_path = model_dir / "metadata.json"
    development_path = model_dir / "development_flight_health_indicators.csv"
    test_path = model_dir / "test_flight_health_indicators.csv"
    for path in (model_path, metadata_path, development_path, test_path):
        if not path.exists():
            raise FileNotFoundError(f"Expected trained-model output is missing: {path}")
    development = pd.read_csv(development_path)
    test = pd.read_csv(test_path)
    scores = pd.concat([development, test], ignore_index=True)
    scores["engine_label"] = scores["split"].str.replace("development", "dev", regex=False) + " engine " + scores["unit"].astype(str)
    return scores.sort_values(["split", "unit", "flight"]).reset_index(drop=True)


def plot_all_engines(scores: pd.DataFrame, output: Path, hi_column: str, metadata: dict[str, object]) -> None:
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(2, 1, figsize=(14, 12), sharex=False, constrained_layout=True)
    colors = {"development": "#2563eb", "test": "#c27c00"}
    titles = {"development": "Development engines", "test": "Test engines"}
    for axis, split in zip(axes, ("development", "test")):
        frame_split = scores[scores["split"] == split]
        for unit, frame in frame_split.groupby("unit", sort=True):
            frame = frame.sort_values("flight")
            axis.plot(
                frame["flight"], frame[hi_column], color=colors[split], linewidth=1.8,
                marker="o", markersize=2.4, alpha=0.9, label=f"engine {int(unit)}",
            )
            healthy = frame[frame["health_stage"] == 1]
            degraded = frame[frame["health_stage"] == 0]
            if not healthy.empty and not degraded.empty:
                axis.axvline(
                    healthy["flight"].max() + 0.5, color="#6b7280", linestyle="--",
                    linewidth=0.8, alpha=0.5,
                )
        axis.set_title(titles[split])
        axis.set_xlabel("Flight")
        axis.set_ylabel("Paper HI (sum of 9 sensor losses)")
        axis.grid(alpha=0.22)
        axis.legend(ncol=6, frameon=False, loc="upper left")
        axis.text(
            0.995, 0.02, f"{frame_split['unit'].nunique()} engines; {len(frame_split)} flights",
            transform=axis.transAxes, ha="right", va="bottom", fontsize=9, color="#4b5563",
        )
    fig.suptitle(
        "N-CMAPSS DS02-006: HI for all development and test engines\n"
        "HI generated by the trained conditional LSTM-AE; dashed lines mark hs=1 to hs=0",
        fontsize=15,
    )
    fig.savefig(output, dpi=220)
    plt.close(fig)


def plot_faceted(scores: pd.DataFrame, output: Path, hi_column: str) -> None:
    import matplotlib.pyplot as plt

    units = sorted(scores["unit"].unique())
    fig, axes = plt.subplots(3, 3, figsize=(15, 12), sharey=True, constrained_layout=True)
    colors = {"development": "#2563eb", "test": "#c27c00"}
    for axis, unit in zip(axes.flat, units):
        frame = scores[scores["unit"] == unit].sort_values("flight")
        split = str(frame["split"].iloc[0])
        axis.plot(frame["flight"], frame[hi_column], color=colors[split], linewidth=1.7, marker="o", markersize=2.2)
        axis.set_title(f"{split}: engine {int(unit)}")
        axis.set_xlabel("Flight")
        axis.set_ylabel("HI")
        axis.grid(alpha=0.2)
        healthy = frame[frame["health_stage"] == 1]
        degraded = frame[frame["health_stage"] == 0]
        if not healthy.empty and not degraded.empty:
            axis.axvline(healthy["flight"].max() + 0.5, color="#6b7280", linestyle="--", linewidth=0.8, alpha=0.5)
    for axis in axes.flat[len(units):]:
        axis.axis("off")
    fig.suptitle("N-CMAPSS DS02-006: individual-engine health indicators", fontsize=15)
    fig.savefig(output, dpi=220)
    plt.close(fig)


def main() -> None:
    args = parse_args()
    output_dir = args.output_dir or args.model_dir / "all_engine_hi"
    output_dir.mkdir(parents=True, exist_ok=True)
    scores = load_scores(args.model_dir)
    scores.to_csv(output_dir / "all_engine_hi.csv", index=False)
    metadata = json.loads((args.model_dir / "metadata.json").read_text())
    metadata["all_engine_plot_hi_column"] = args.hi_column
    (output_dir / "plot_metadata.json").write_text(json.dumps(metadata, indent=2))
    plot_all_engines(scores, output_dir / "all_engines_dev_test_hi.png", args.hi_column, metadata)
    plot_faceted(scores, output_dir / "individual_engine_hi.png", args.hi_column)
    print(f"saved all-engine N-CMAPSS HI plots to {output_dir}")


if __name__ == "__main__":
    main()
